
title: My Resume # your title
url: 'https://y570pc.github.io'
baseurl: '/pic' #change it according to your repository name



# Profile information
yourname: 炎季宏的博客  ## put your name



## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
